[A]
width = 1080
height = 1080
type = "text"
text = "A"
size = 180
position = ['20%', '35%']

[B]
width = 1080
height = 1080
type = "text"
text = "B"
size = 180
position = ['20%', '35%']

[C]
width = 1080
height = 1080
type = "text"
text = "C"
size = 180
position = ['20%', '35%']

[D]
width = 1080
height = 1080
type = "text"
text = "D"
size = 180
position = ['20%', '35%']

[E]
width = 1080
height = 1080
type = "text"
text = "E"
size = 180
position = ['20%', '35%']

[F]
width = 1080
height = 1080
type = "text"
text = "F"
size = 180
position = ['20%', '35%']

[G]
width = 1080
height = 1080
type = "text"
text = "G"
size = 180
position = ['20%', '35%']

[H]
width = 1080
height = 1080
type = "text"
text = "H"
size = 180
position = ['20%', '35%']

[I]
width = 1080
height = 1080
type = "text"
text = "I"
size = 180
position = ['20%', '35%']

[J]
width = 1080
height = 1080
type = "text"
text = "J"
size = 180
position = ['20%', '35%']

[K]
width = 1080
height = 1080
type = "text"
text = "K"
size = 180
position = ['20%', '35%']

[L]
width = 1080
height = 1080
type = "text"
text = "L"
size = 180
position = ['20%', '35%']

[M]
width = 1080
height = 1080
type = "text"
text = "M"
size = 180
position = ['20%', '35%']

[N]
width = 1080
height = 1080
type = "text"
text = "N"
size = 180
position = ['20%', '35%']

[O]
width = 1080
height = 1080
type = "text"
text = "O"
size = 180
position = ['20%', '35%']

[P]
width = 1080
height = 1080
type = "text"
text = "P"
size = 180
position = ['20%', '35%']

[Q]
width = 1080
height = 1080
type = "text"
text = "Q"
size = 180
position = ['20%', '35%']

[R]
width = 1080
height = 1080
type = "text"
text = "R"
size = 180
position = ['20%', '35%']

[S]
width = 1080
height = 1080
type = "text"
text = "S"
size = 180
position = ['20%', '35%']

[T]
width = 1080
height = 1080
type = "text"
text = "T"
size = 180
position = ['20%', '35%']

[U]
width = 1080
height = 1080
type = "text"
text = "U"
size = 180
position = ['20%', '35%']

[V]
width = 1080
height = 1080
type = "text"
text = "V"
size = 180
position = ['20%', '35%']

[W]
width = 1080
height = 1080
type = "text"
text = "W"
size = 180
position = ['20%', '35%']

[X]
width = 1080
height = 1080
type = "text"
text = "X"
size = 180
position = ['20%', '35%']

[Y]
width = 1080
height = 1080
type = "text"
text = "Y"
size = 180
position = ['20%', '35%']

[Z]
width = 1080
height = 1080
type = "text"
text = "Z"
size = 180
position = ['20%', '35%']

[alt_gr]
width = 1080
height = 1080
type = "text"
text = "alt gr"
size = 140
position = ['20%', '35%']

[maj]
width = 1600
height = 1080
type = "text"
text = "maj"
size = 140
position = [500, 400]

[shift]
width = 1600
height = 1080
type = "text"
text = "shift"
size = 140
position = [100, 700]

[ctrl]
width = 1080
height = 1080
type = "text"
text = "ctrl"
size = 140
position = [100, 100]

[alt]
width = 1080
height = 1080
type = "text"
text = "alt"
size = 140
position = [100, 100]

[space]
width = 2080
height = 1080
type = "text"
text = "space"
size = 140
position = [100, 100]

[win]
width = 1080
height = 1080
type = "image"
text = "windows.png"
size = 450
position = [100, 100]

[up]
width = 1080
height = 1080
type = "image"
text = "up.png"
size = 450
position = [100, 100]

[down]
width = 1080
height = 1080
type = "image"
text = "down.png"
size = 450
position = [100, 100]

[left]
width = 1080
height = 1080
type = "image"
text = "left.png"
size = 450
position = [100, 100]

[right]
width = 1080
height = 1080
type = "image"
text = "right.png"
size = 450
position = [100, 100]

[capslock]
width = 1080
height = 1080
type = "image"
text = "capslock.png"
size = 450
position = [100, 100]

