name: Generate Keys
on:
  push:
    paths:
      - 'config.toml'

jobs:
  generate_keys:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Generate Keys
      run: python generate_keys.py
