name: Generate Keys
on:
  workflow_dispatch:
  push:
    paths:
      - 'config.toml'
    
jobs:
  generate_keys:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: pip install toml
    - name: Generate Keys
      run: python generate_keys.py
    - name: Commit files
      run: |
        git config --local user.email ${{ vars.USER_EMAIL }}
        git config --local user.name ${{ vars.USER_NAME }}
        git add .
        git commit -m "Generated SVG files"
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
